services:
  backend:
    build: ./backend
    expose:
      - "8000"
    env_file: .env
    restart: unless-stopped
    networks:
      - internal
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mellow-backend.rule=Host(`api.mellow.lat`)"
      - "traefik.http.routers.mellow-backend.entrypoints=websecure"
      - "traefik.http.routers.mellow-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.mellow-backend.loadbalancer.server.port=8000"

networks:
  internal:
    driver: bridge
  dokploy-network:
    external: true
